name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight (UTC)
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This issue has been marked as stale due to inactivity. Please update if it is still relevant."
          stale-pr-message: "This pull request has been marked as stale due to inactivity. Please update if it is still relevant."
          stale-issue-label: "needs-attention"
          stale-pr-label: "needs-review"
          days-before-issue-stale: 60        # Number of days of inactivity before marking issues as stale
          days-before-pr-stale: 45           # Number of days of inactivity before marking PRs as stale
          days-before-issue-close: -1        # Do not automatically close issues
          days-before-pr-close: -1           # Do not automatically close PRs
          exempt-issue-labels: "hold,feature,in progress"  # Exempt these labels from being marked stale
          exempt-pr-labels: "hold"           # Exempt these labels from being marked stale
          remove-issue-stale-when-updated: true  # Remove stale label when issue is updated
          remove-pr-stale-when-updated: true     # Remove stale label when PR is updated
          include-only-assigned: false           # Include issues even if they have an assignee
