
name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight (UTC)
  workflow_dispatch:

permissions:
  contents: write # only for delete-branch option
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          days-before-stale: 60
          days-before-stale-pr: 45
          days-before-close: -1
          stale-issue-message: "This issue has been marked as stale due to inactivity. Please update if it is still relevant"
          stale-pr-message: "This pull request has been marked as stale due to inactivity. Please update if it is still relevant."
          close-issue-message: ""
          close-pr-message: ""
          stale-issue-label: "needs-attention"
          stale-pr-label: "needs-review"
          exempt-issue-labels: "hold,feature,in progress"
          exempt-pr-labels: "hold"
          only-labels: ""
          remove-stale-when-updated: true
          ignore-issue-assignees: false
